ui:
    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: false

    extensions:
        FriendsOfBehat\SymfonyExtension:
            bootstrap: behat-bootstrap.php
            kernel:
                path: src/BehatKernel.php
                class: BehatKernel
                environment: test

        FriendsOfBehat\MinkDebugExtension:
            directory: etc/build
            clean_start: false
            screenshot: true

        Behat\MinkExtension:
            base_url: "http://localhost:9080/index_test.php"
            default_session: panther
            sessions:
                panther:
                    panther:
                        manager_options:
                            connection_timeout_in_ms: 5000
                            request_timeout_in_ms: 120000
                            chromedriver_arguments:
                                - --log-path=etc/build/chromedriver.log
                                - --verbose
                            capabilities:
                                acceptSslCerts: true
                                acceptInsecureCerts: true
                                unexpectedAlertBehaviour: accept
                        options:
                            browser: chrome
                            browser_arguments:
                                - --window-size=1200,1000
                                - --headless
                                - --no-sandbox
                                - --disable-dev-shm-usage
                                - --disable-gpu
                                - --disable-infobars
                                - --disable-features=TranslateUI
                                - --disable-translate
                                - --disable-popup-blocking
                                - --disable-blink-features=AutomationControlled
                                - --disable-component-extensions-with-background-pages
                                - --disable-background-networking
                                - --disable-dev-tools
                                - --disable-extensions
                                - --guest
            show_auto: false

        Robertfausk\Behat\PantherExtension: ~

    gherkin:
        filters:
            tags: '@ui&&~@ui_precision&&~@ui_pimcore&&~@wip'
